name: testing

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: pip
          cache-dependency-path: pyproject.toml

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[strict,tests]
          pip install prospector[with_mypy,with_bandit]

    - name: Lint with prospector
      run: |
        prospector src/mpmorph

    - name: Lint with black
      run: |
        black --check --diff --color src/mpmorph

  test:
    strategy:
      max-parallel: 6
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.9', '3.10']
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        python-version: ${{ matrix.python-version }}
        activate-environment: foo

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .

    - name: Test with pytest
      run: |
        pytest --cov=src/mpmorph --cov-report=xml
